### ISSUE TITLE
Move default configuration path to `/etc/docket/`

### ISSUE THREAD

**Issue by dcode** [rocknsm/docket#12]
Default configuration should be located at `/etc/docket` per Fedora packaging guidelines.

**Comment by JeffKwasha** [comment]
unsure if you mean /etc/docket/FILES or /etc/docket.conf

I'll assume the former: #16 attempts to load the file at:
env = environment('DOCKET_CONF') or environment('APP_CONF') // from here onwards
/etc/docket/env
/etc/docket/docket 
/etc/env

It will add ".yaml" to these paths if it fails to find a file without it.
