### ISSUE TITLE
Allow re-download of results

### ISSUE THREAD

**Issue by dcode** [rocknsm/docket#6]
The results are kept on the system for a default period of 1 hour. Rather than the current blocking mode we use, we should perform a redirect to a result URI. This would allow us to re-use the existing PCAP vs. rerunning the query every time.

Needs more flushing out how this would best work.

**Comment by JeffKwasha** [comment]
#16 implements this.
Queries return json including an identifier and a url.
the identifier can be used with a number of API calls to obtain more or updated info: status, ids, urls
The GUI displays the identifier / url / request time / request state
The GUI allows previously run requests to be searched for / retrieved.
